-- Esquema online para Planilla Inventario.
-- Ejecutar completo en Supabase > SQL Editor.

create table if not exists public.productos (
    id text primary key,
    categoria text not null,
    marca text not null default '',
    modelo_detalle text not null default '',
    codigo_pieza text not null default '',
    stock_actual integer not null default 0 check (stock_actual >= 0),
    stock_minimo integer not null default 0 check (stock_minimo >= 0),
    unidad text not null default 'UNIDAD',
    requiere_serial boolean not null default false,
    actualizado_en timestamptz not null default now()
);

create table if not exists public.unidades_serializadas (
    id bigint generated by default as identity primary key,
    numero_marcado text not null,
    tipo_articulo text not null,
    id_producto text not null references public.productos(id),
    marca text not null default '',
    modelo_medida text not null default '',
    estado text not null default 'EN STOCK',
    vehiculo_actual text not null default '',
    fecha_ultimo_movimiento timestamptz,
    historial jsonb not null default '[]'::jsonb,
    unique (numero_marcado, tipo_articulo)
);

create table if not exists public.responsables (
    nombre text primary key,
    pin text not null default '1234'
);

create table if not exists public.receptores (
    nombre text primary key,
    email text not null default '',
    gerencia text not null default '',
    actualizado_en timestamptz not null default now()
);

create table if not exists public.remitos (
    nro_remito text primary key,
    fecha date not null,
    hora time,
    responsable text not null default '',
    tipo_remito text not null,
    articulo_principal text not null default '',
    marca text not null default '',
    modelo text not null default '',
    cantidad integer not null default 0,
    gerencia text not null default '',
    patente text not null default '',
    receptor text not null default '',
    email_receptor text not null default '',
    region_edenor text not null default '',
    numero_factura text not null default '',
    foto_factura text not null default '',
    observaciones text not null default '',
    estado text not null default 'Procesado',
    fecha_procesamiento timestamptz not null default now()
);

create table if not exists public.remito_items (
    id bigint generated by default as identity primary key,
    nro_remito text not null references public.remitos(nro_remito) on delete cascade,
    id_producto text not null references public.productos(id),
    categoria text not null default '',
    marca text not null default '',
    descripcion text not null default '',
    codigo_pieza text not null default '',
    cantidad integer not null default 0,
    numeros_seriales text not null default ''
);

create table if not exists public.patentes_no_catalogadas (
    patente text primary key,
    gerencia text not null default '',
    receptor text not null default '',
    remito_id text not null default '',
    fecha_uso timestamptz not null default now(),
    estado text not null default 'Pendiente de catalogar',
    observaciones text not null default ''
);

create table if not exists public.auditoria (
    id bigint generated by default as identity primary key,
    creado_en timestamptz not null default now(),
    usuario text not null default '',
    accion text not null,
    entidad text not null,
    entidad_id text not null default '',
    detalle jsonb not null default '{}'::jsonb
);

create index if not exists idx_unidades_estado on public.unidades_serializadas (estado);
create index if not exists idx_unidades_vehiculo on public.unidades_serializadas (vehiculo_actual);
create index if not exists idx_remitos_fecha on public.remitos (fecha desc);
create index if not exists idx_remito_items_remito on public.remito_items (nro_remito);
create index if not exists idx_auditoria_entidad on public.auditoria (entidad, entidad_id);

create or replace view public.informe_remitos as
select
    r.nro_remito,
    r.fecha,
    r.hora,
    r.responsable,
    r.tipo_remito,
    r.articulo_principal,
    r.marca,
    r.modelo,
    r.cantidad,
    r.gerencia,
    r.patente,
    r.receptor,
    r.email_receptor,
    r.region_edenor,
    r.numero_factura,
    r.foto_factura,
    r.observaciones,
    r.estado,
    r.fecha_procesamiento,
    count(i.id) as cantidad_de_items
from public.remitos r
left join public.remito_items i on i.nro_remito = r.nro_remito
group by r.nro_remito;
